import { z } from 'zod';
export const trainSchema = z.object({
id: z.string(),
trainNumber: z.string().min(1, 'Train number is required'),
departureTime: z.string().regex(/^\d{2}:\d{2}$/, 'Format must be HH:MM'),
platform: z.string().min(1, 'Platform is required'),
carriages: z.number().min(1, 'Must have at least 1 carriage'),
seats: z.number().min(1, 'Must have at least 1 seat'),
arrivalStation: z.string().min(1, 'Arrival station is required'),
arrivalTime: z.string().regex(/^\d{2}:\d{2}$/, 'Format must be HH:MM'),
status: z.enum(['on-time', 'delayed', 'cancelled']).default('on-time'),
});
export type Train = z.infer<typeof trainSchema>;
export const trainSearchSchema = z.object({
trainNumber: z.string().optional(),
platform: z.string().optional(),
arrivalStation: z.string().optional(),
status: z.enum(['all', 'on-time', 'delayed', 'cancelled']).default('all'),
});
export type TrainSearch = z.infer<typeof trainSearchSchema>;
export const mockTrains: Train[] = [
{
id: '1',
trainNumber: 'IC-001',
departureTime: '08:15',
platform: '1',
carriages: 8,
seats: 280,
arrivalStation: 'Kaunas',
arrivalTime: '09:45',
status: 'on-time',
},
{
id: '2',
trainNumber: 'EC-002',
departureTime: '09:30',
platform: '2',
carriages: 10,
seats: 350,
arrivalStation: 'Šiauliai',
arrivalTime: '11:20',
status: 'on-time',
},
{
id: '3',
trainNumber: 'R-003',
departureTime: '10:00',
platform: '3',
carriages: 6,
seats: 200,
arrivalStation: 'Panevėžys',
arrivalTime: '10:50',
status: 'delayed',
},
{
id: '4',
trainNumber: 'IC-004',
departureTime: '11:15',
platform: '1',
carriages: 8,
seats: 280,
arrivalStation: 'Alytus',
arrivalTime: '12:30',
status: 'on-time',
},
{
id: '5',
trainNumber: 'EC-005',
departureTime: '13:00',
platform: '4',
carriages: 10,
seats: 350,
arrivalStation: 'Vilkaviškis',
arrivalTime: '14:45',
status: 'on-time',
},
{
id: '6',
trainNumber: 'R-006',
departureTime: '14:30',
platform: '2',
carriages: 6,
seats: 200,
arrivalStation: 'Tauragė',
arrivalTime: '16:15',
status: 'cancelled',
},
{
id: '7',
trainNumber: 'IC-007',
departureTime: '15:45',
platform: '3',
carriages: 8,
seats: 280,
arrivalStation: 'Kaunas',
arrivalTime: '17:15',
status: 'on-time',
},
{
id: '8',
trainNumber: 'EC-008',
departureTime: '17:00',
platform: '1',
carriages: 10,
seats: 350,
arrivalStation: 'Šiauliai',
arrivalTime: '18:50',
status: 'on-time',
},
];